# Generated by Django 6.0.1 on 2026-01-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=10)),
                ('numero_endereco', models.IntegerField()),
                ('estado_civil', models.CharField(choices=[('S', 'Solteira(o)'), ('C', 'Casada(o)'), ('D', 'Divorciada(o)'), ('V', 'Viuva(o)'), ('O', 'Outro')], default='S', max_length=1)),
                ('profissao', models.CharField(max_length=150)),
                ('formacao_educacional', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DadosClinicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao', models.CharField(max_length=255)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3)),
                ('pressao_sistolica', models.IntegerField()),
                ('pressao_diastolica', models.IntegerField()),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('frequencia_respiratoria', models.IntegerField()),
                ('saturacao_oxigenio', models.CharField(max_length=4)),
                ('glicemia', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('alergias', models.CharField(max_length=255)),
                ('medicamentos', models.CharField(max_length=255)),
                ('condicao_medica', models.CharField(max_length=255)),
                ('internacao_anterior', models.CharField(max_length=255)),
                ('cirurgia_anterior', models.CharField(max_length=255)),
                ('doencas_familiares', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prontuario.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloManchester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('muito_alto', 'Muito Alto')], default='baixo', max_length=20)),
                ('anotacoes', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prontuario.paciente')),
            ],
        ),
    ]
