# Generated by Django 6.0.1 on 2026-01-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosClinicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao', models.CharField(max_length=255)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3)),
                ('pressao_arterial', models.IntegerField()),
                ('temperatura', models.CharField(max_length=4)),
                ('frequencia_respiratoria', models.IntegerField(max_length=2)),
                ('saturacao_oxigenio', models.CharField(max_length=4)),
                ('glicemia', models.IntegerField(max_length=3)),
                ('altura', models.IntegerField(max_length=4)),
                ('peso', models.IntegerField(max_length=4)),
                ('alergias', models.CharField(max_length=255)),
                ('medicamentos', models.CharField(max_length=255)),
                ('condicao_medica', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=10)),
                ('numero_endereco', models.IntegerField()),
                ('estado_civil', models.CharField(choices=[('S', 'Solteira(o)'), ('C', 'Casada(o)'), ('D', 'Divorciada(o)'), ('V', 'Viuva(o)'), ('O', 'Outro')], default='S', max_length=1)),
                ('profissao', models.CharField(max_length=150)),
                ('formacao_educacional', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PrevioHistoricoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internacao_anterior', models.CharField(max_length=255)),
                ('cirurgia_anterior', models.CharField(max_length=255)),
                ('doencas_familiares', models.CharField(max_length=255)),
            ],
        ),
    ]
